name: complex
on: push
jobs:
 windows:
 runs-on: windows-latest
 steps:
 - run: date
 ubuntu:
  runs-on: ubuntu-latest
  steps:
 - run: date
 macos:
  runs-on: macos-latest
 steps:
 - run: date
 depencies:
 needs: [windows, ubuntu,macos]
 runs-on: windows-latest
 steps:
  - run: date
